image: node:8

cache:
  paths:
  - node_modules

stages:
  - build
  - deploy
  
grunt_build:
  stage: build
  script:
    - apt-get update -yq
    - apt-get install git
    - apt-get install -y zip gzip tar
    - npm install -g bower grunt-cli
    - npm install
    - bower install --allow-root --no-interactive
    - grunt
  artifacts:
    paths:
      - ./${CI_PROJECT_NAME}.zip
      - ./doc


marketplace_deploy:
  stage: deploy
  dependencies: 
    - grunt_build
  only:
    - master
  script:
    - ls
    - curl -F "file=@./${CI_PROJECT_NAME}.zip" http://marketplace.webpich.com/api/marketplace/spa/token-$MARKETPLACE_TOKEN